### ISSUE TITLE
refactor regexes for filecoin verifier tools

### ISSUE THREAD

**Issue by fabriziogianni7** [keyko-io/filecoin-verifier-tools#149]
# Description
one of the function this library has is to parse the content of the github issue.
we get as an input the body of the issue and we extract some info from it.
as you can see now, the parsing functions are very long and we are hardcoding the regexes, and using some helper function like [this](https://github.com/keyko-io/filecoin-verifier-tools/blob/571f3fdff2bd41da1877a14ad1ffb37ea7cc46bb/utils/common-utils.js#L3)

## To do
all the content passed in (the issue body) should be trimmered and parsed using lookahead / lookbehind
there is an [example](https://github.com/keyko-io/filecoin-verifier-tools/blob/571f3fdff2bd41da1877a14ad1ffb37ea7cc46bb/utils/large-issue-parser.js#L118) of how can the parsing function be.
it is a little bit more dynamic:

```
 for (const [k, v] of Object.entries(data)) {
    const rg = new RegExp(`(?<=${v})(.*?)(?=#)`) //building the regex dynamically
    const regexIsNull = !trimmed.match(rg) || !trimmed.match(rg).length || !trimmed.match(rg)[0] //checking if the return value is null
   [other stuff]
    }
```
note that here we're not using any helper function to execute the regex

I suggest to use https://regex101.com/ to test regex you build

## The goal 
- have less code and a clearer view of the regexes.
- all the test cases should pass
- all the functions should return the same object structure than before

**Comment by fabriziogianni7** [comment]
@huseyincansoylu 
you can delete function `parseOtherInfoIssue` we are not using this

**Comment by fabriziogianni7** [comment]
@huseyincansoylu 
I made some PR you need to have a look bc you need to ad a regex in your refactoring: it is needed to parse the uuid from the requests.
https://github.com/keyko-io/filecoin-verifier-tools/pull/153/files
i’m merging this in master, but you should add this to the refactor of the corresponding function
also adding a comment in your issue so you don’t forget

**Comment by fabriziogianni7** [comment]
I also suggest to go through all the project and see if we need all of the functions over there cause I believe some are not used anymore, for instance the following --> 
https://github.com/keyko-io/filecoin-verifier-tools/blob/571f3fdff2bd41da1877a14ad1ffb37ea7cc46bb/utils/large-issue-parser.js#L6
https://github.com/keyko-io/filecoin-verifier-tools/blob/571f3fdff2bd41da1877a14ad1ffb37ea7cc46bb/utils/large-issue-parser.js#L204
https://github.com/keyko-io/filecoin-verifier-tools/blob/571f3fdff2bd41da1877a14ad1ffb37ea7cc46bb/utils/large-issue-parser.js#L166
(for the last 2: https://github.com/keyko-io/filecoin-verifier-tools/blob/571f3fdff2bd41da1877a14ad1ffb37ea7cc46bb/utils/large-issue-parser.js#L166 is doing the job)

**Comment by jbesraa** [comment]
https://github.com/keyko-io/filecoin-large-clients-onboarding-bot/pull/119
