### ISSUE TITLE
Rename repo + npm package to something filecoin specific?

### ISSUE THREAD

**Issue by jbenet** [keyko-io/filecoin-verifier-tools#18]
Right now the library is called `js-hamt-ipld`. That would imply the library is simply an implementation of a [HAMT](https://en.wikipedia.org/wiki/Hash_array_mapped_trie) (Hash array mapped trie) in javascript, with IPLD datastructures. But that is only a small part of the library, namely [this file](https://github.com/keyko-io/js-hamt-ipld/blob/master/hamt/hamt.js).

The majority of the library is tooling for filecoin verified clients, including signing transactions and so on.

I think the library, [the repo](https://github.com/keyko-io/js-hamt-ipld), and [the npm package](https://www.npmjs.com/package/@keyko-io/js-hamt-ipld) should all be renamed to something like `js-fil-verifier-tools` or you could come up with an unrelated name (kind of like `lotus` is an unrelated name -- unlike `go-filecoin`).

**Comment by aaitor** [comment]
Repo name changed to `filecoin-verifier-tools`. 
NPM package will have the new name in the new release of the library.
