### ISSUE TITLE
Implement new API methods to provide the info needed in the frontend

### ISSUE THREAD

**Issue by josepablofm78** [keyko-io/filecoin-verifier-tools#33]
The design of the frontend app includes information we are not getting from the net right now, as we were focus on the core functionality.

Some of this info could be get from the state tree, or maybe performing some kind of additional computation over the data we are getting now. 

The API should implement new methods to get this info

**Comment by jernejpregelj** [comment]
Working on specs here:

https://docs.google.com/document/d/1uD6mvCzQzX_cDFQVX5cQMdKpKPWwoPqrmSRqModDxt8/edit
